-- Enable UUID extension for QR codes
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Master: Transaction Types
CREATE TABLE m_transaction_type (
    transaction_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type_name VARCHAR(100) NOT NULL,
    foundation_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Master: Buildings
CREATE TABLE m_buildings (
    building_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_name VARCHAR(100) NOT NULL,
    foundation_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Master: Rooms
CREATE TABLE m_rooms (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_name VARCHAR(100) NOT NULL,
    floor VARCHAR(50),
    building_id BIGINT REFERENCES m_buildings(building_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Master: Item Types (Categories)
CREATE TABLE m_item_types (
    item_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_type_name VARCHAR(100) NOT NULL,
    description TEXT,
    foundation_id BIGINT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 5. Master: Items (Products)
CREATE TABLE m_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(150) NOT NULL,
    unit VARCHAR(50),
    item_type_id BIGINT REFERENCES m_item_types(item_type_id) ON DELETE SET NULL,
    useful_life_months INTEGER DEFAULT 60, -- 5 years default for depreciation
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 6. Transactions Header
CREATE TABLE t_inventory_transactions (
    inventory_transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date DATE NOT NULL,
    transaction_number VARCHAR(100) UNIQUE NOT NULL,
    status VARCHAR(50) DEFAULT 'COMPLETED',
    start_date DATE,
    end_date DATE,
    evidence_file VARCHAR(255),
    source_of_funds VARCHAR(100),
    total_budget DECIMAL(15,2),
    budget_realization DECIMAL(15,2),
    transaction_type_id BIGINT REFERENCES m_transaction_type(transaction_type_id) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 7. Inventory (Actual Physical Stock Batch)
CREATE TABLE t_inventory (
    inventory_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID DEFAULT uuid_generate_v4() UNIQUE NOT NULL, -- For Public QR Code lookups
    quantity INTEGER NOT NULL DEFAULT 0,
    price DECIMAL(15,2) NOT NULL DEFAULT 0,
    salvage_value DECIMAL(15,2) DEFAULT 0, -- Value at end of useful life
    specification TEXT,
    status VARCHAR(50) DEFAULT 'GOOD',
    photo VARCHAR(255),
    description TEXT,
    merk VARCHAR(100),
    barcode VARCHAR(100),
    expired_date DATE,
    purchase_date DATE DEFAULT CURRENT_DATE, -- Base date for depreciation
    item_id BIGINT REFERENCES m_items(item_id) ON DELETE CASCADE,
    inventory_transaction_id BIGINT REFERENCES t_inventory_transactions(inventory_transaction_id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 8. Inventory Location Assignment (Distribution)
CREATE TABLE t_inventory_room (
    inventory_room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INTEGER NOT NULL DEFAULT 1, -- Added so we can distribute partial batches
    status VARCHAR(50) DEFAULT 'ACTIVE',
    inventory_date DATE NOT NULL DEFAULT CURRENT_DATE,
    inventory_id BIGINT REFERENCES t_inventory(inventory_id) ON DELETE CASCADE,
    room_id BIGINT REFERENCES m_rooms(room_id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Function: Calculate Depreciation (Straight-Line)
CREATE OR REPLACE FUNCTION calculate_depreciation(inv_id BIGINT)
RETURNS DECIMAL AS $$
DECLARE
    v_price DECIMAL;
    v_salvage DECIMAL;
    v_purchase_date DATE;
    v_useful_months INTEGER;
    v_months_passed INTEGER;
    v_depreciation_per_month DECIMAL;
    v_current_value DECIMAL;
BEGIN
    -- Get asset details
    SELECT 
        i.price, 
        i.salvage_value, 
        i.purchase_date, 
        m.useful_life_months
    INTO 
        v_price, v_salvage, v_purchase_date, v_useful_months
    FROM t_inventory i
    JOIN m_items m ON i.item_id = m.item_id
    WHERE i.inventory_id = inv_id;

    -- If no useful life or it's 0, no depreciation
    IF v_useful_months IS NULL OR v_useful_months <= 0 THEN
        RETURN v_price;
    END IF;

    -- Calculate months passed since purchase
    v_months_passed := (DATE_PART('year', CURRENT_DATE) - DATE_PART('year', v_purchase_date)) * 12 +
                       (DATE_PART('month', CURRENT_DATE) - DATE_PART('month', v_purchase_date));

    -- If not even a month has passed, return full price
    IF v_months_passed <= 0 THEN
        RETURN v_price;
    END IF;

    -- If it has passed its useful life, return salvage value
    IF v_months_passed >= v_useful_months THEN
        RETURN v_salvage;
    END IF;

    -- Calculate straight-line depreciation
    v_depreciation_per_month := (v_price - v_salvage) / v_useful_months;
    v_current_value := v_price - (v_depreciation_per_month * v_months_passed);

    RETURN v_current_value;
END;
$$ LANGUAGE plpgsql;

-- View: Inventory with Real-Time Depreciation
-- We can query this view directly from Next.js to get the calculated value instantly
CREATE OR REPLACE VIEW v_inventory_depreciation AS
SELECT 
    i.*,
    calculate_depreciation(i.inventory_id) AS current_depreciated_value
FROM t_inventory i;
